### ISSUE TITLE
venv path typo?

### ISSUE THREAD

**Issue by harukaxxxx** [KohakuBlueleaf/Kohaku-NAI#2]
https://github.com/KohakuBlueleaf/Kohaku-NAI/blob/afb0d6c99a2a8ea8d8dc06f0da55dad145f73482/README.md?plain=1#L40
Trying run standalone client and have error on setup step 4.
It should be `./venv/Scripts/activate ` not `./venv/Script/activate ` isn't it?

**Comment by KohakuBlueleaf** [comment]
Yes
Will change it later
